version: "3.8"

services:
  vault:
    image: hashicorp/vault-enterprise:1.15-ent
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_LICENSE: ${VAULT_LICENSE}
    volumes:
      - ./vault/config/vault1.hcl:/vault/config/vault1.hcl
      - ./vault_data:/vault/data  # Raft data will be stored here
    cap_add:
      - IPC_LOCK
    command: "vault server -config=/vault/config/vault1.hcl"
    ports:
      - "8200:8200"
      - "9102:9102" # Expose telemetry on port 9102
    networks:
      hashi_vpcbr:
        ipv4_address: 10.5.0.12 # Replace with an unused IP in your subnet

networks:
  hashi_vpcbr:
    external: true
